analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.677927
  lightness: 0.996621
  rhythmicContrast: 0.515765
  saturation: 0.495495
cta: {}
layout_spectrum: 0.6536301437299699
name: ChefLayugTravels
opengraph: {}
purpose: []
typography_spectrum: 0.02906407229602337
